import React from "react";
import { Link } from "react-router-dom";
import { AlertTriangle } from "lucide-react";

/** Persistent notice: signals are educational tools, not financial advice. */
const DisclaimerNotice = () => (
  <div
    className="p-3 rounded-lg bg-warning-50 dark:bg-warning-900/30 border border-warning-100 dark:border-warning-800 flex items-start gap-2"
    data-testid="ai-analysis-disclaimer"
  >
    <AlertTriangle className="w-4 h-4 text-warning-600 dark:text-warning-400 mt-0.5 flex-shrink-0" />
    <p className="text-sm text-warning-700 dark:text-warning-300">
      These signals are generated by transparent technical rules on ~15-minute-delayed data and are
      for education and journaling only — not financial advice. Futures trading involves substantial
      risk of loss. See our{" "}
      <Link to="/disclaimer" className="underline font-medium" data-testid="ai-analysis-disclaimer-link">
        full disclaimer
      </Link>
      .
    </p>
  </div>
);

export default DisclaimerNotice;
